services:

  jellyfin:
    image: jellyfin:latest
    ports: 
      - "8000:8000"
    networks:
      - internal-net
    volumes:
      - media-data:/media/data 
    env_file:
      - contrib/env
  db:
    image: docker.io/postgres:bookworm
    networks:
      - internal-net
    env_file:
      - contrib/env

volumes:
  media-data:

networks:
  internal-net: {}