services:

  jellyfin:
    image: jellyfin-magicka:latest
    ports: 
      - "8000:8000"
    volumes:
      - media-data:/media/data 
    env_file:
      - contrib/env
  db:
    image: docker.io/postgres:bookworm
    env_file:
      - contrib/env

volumes:
  media-data:
