

name: Jellyfin Magicka CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-22.04
    steps:
    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v2
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix
    - name: run mix
      run: mix deps.get compile