

name: Jellyfin Magicka CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Restore Cached ASDF
      uses: actions/cache/restore@v3
      id: cache
      with:
        path: ~/.asdf
        key: ${{ runner.os }}-${{ hashFiles('.tool-versions') }}
    - name: Install ASDF
      if: steps.cache.outputs.cache-hit != 'true'
      uses: asdf-vm/actions/install@v2
    
    - name: Restore Cached Elixir Deps
      uses: actions/cache@v2
      id: cache-elixir
      with:
        path: deps
        key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
    
    - name: mix deps.get
      if: steps.cache-elixir.outputs.cache-hit != 'true'
      run: mix deps.get
    
    - name: mix compile
      run: mix compile