

name: Jellyfin Magicka CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  setup:
    name: setup env
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: ASDF (get cached)
      uses: actions/cache/restore@v3
      id: cache-asdf
      with:
        path: ~/.asdf
        key: ${{ runner.os }}-${{ hashFiles('.tool-versions') }}
    - name: ASDF (install)
      if: steps.cache-asdf.outputs.cache-hit != 'true'
      uses: asdf-vm/actions/install@v2
    - name: ASDF (store cache)
      if: steps.cache-asdf.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: ~/.asdf
        key: ${{ runner.os }}-${{ hashFiles('.tool-versions') }}
    - name: Elixir (get cached)
      uses: actions/cache/restore@v3
      id: cache-elixir
      with:
        path: deps
        key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
    - name: Elixir (mix deps)
      if: steps.cache-elixir.outputs.cache-hit != 'true'
      run: mix deps.get deps.compile
    - name: Elixir (store cached)
      if: steps.cache-elixir.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: deps
        key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}

  build:
    name: build
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: ASDF (get cached)
        uses: actions/cache/restore@v3
        id: cache-asdf
        with:
          path: ~/.asdf
          key: ${{ runner.os }}-${{ hashFiles('.tool-versions') }}
      - name: ASDF (install)
        uses: asdf-vm/actions/install@v2
      - name: Mix (get cached)
        uses: actions/cache/restore@v3
        id: cache-elixir
        with:
          path: deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
      - name: Elixir (mix deps)
        run: mix deps.get deps.compile
      - name: webui (get cached)
        uses: actions/cache/restore@v3
        with:
          path: _build/dev/lib/jellyfin/priv/web
          key: ${{ runner.os }}-${{ hashFiles('external/jellyfin-web/package-lock.json') }}
      - name: mix compile
        run: mix jellyfin.compile
      - name: webui (store cached)
        uses: actions/cache/save@v3
        with:
          path: _build/dev/lib/jellyfin/priv/web
          key: ${{ runner.os }}-${{ hashFiles('external/jellyfin-web/package-lock.json') }}
