

name: Jellyfin Magicka CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-22.04
    steps:
    - name: check out source code
      uses: actions/checkout@v2
    - uses: asdf-vm/actions/install@v2
    - name: build it
      run: mix deps.get compile